### ISSUE TITLE
Report is_failed function error

### ISSUE THREAD

**Issue by dark-lbp** [cisco-sas/kitty#14]
when i use kitty to fuzzing something i can't got report from controller or monitor.then i use this code blow to check why and may got the probom.
```
>>> from kitty.data.report import Report
>>> subreport = Report('subreport')
>>> subreport.add('failed','got some error')
>>> report=Report('all')
>>> report.add('subreport1',subreport)
>>> subreport.is_failed()
'got some error'
>>> report.is_failed()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/kitty-0.6.1-py2.7.egg/kitty/data/report.py", line 166, in is_failed
    failed |= subreport.is_failed()
TypeError: unsupported operand type(s) for |=: 'bool' and 'str'

```

**Comment by dark-lbp** [comment]
should i change it to 
```
    def is_failed(self):
        '''
        :return: True if the report or any sub report indicates failure.
        '''
        failed = self.get('failed')
        for subreport in self._sub_reports.values():
            failed |= bool(subreport.is_failed())
        return failed
```

will this cause other issue?

**Comment by BinyaminSharet** [comment]
No need to change the function.
The API just works a little different then what you expected:
There are two ways to fail a report, the first is by setting the failure itself and the failure reason separately:

```
report.add('failed', True)
report.add('failure reason', 'got some error')
```

The other is to use the [`failed()`](https://kitty.readthedocs.org/en/latest/kitty.data.report.html?highlight=report#kitty.data.report.Report.failed) method, which accepts the reason as well:

```
report.failed('got some error')
```

**Comment by BinyaminSharet** [comment]
@dark-lbp please let me know if it solved the issue for you, so I can close it.

**Comment by dark-lbp** [comment]
@BinyaminSharet It solved the issue,Thanks.
