### ISSUE TITLE
Add kitty-option: validate - to rerun all the failed/error tests

### ISSUE THREAD

**Issue by 0xd3d0** [cisco-sas/kitty#26]
This could be done with a session file - where all tests with status of error/failed would be re-tested.
A new session file should be created for the second run.

If data model has changed - we cannot use the session file - consider saving the data-model in the session file to make it self-sufficient (?)

Do we need to be able to pass test numbers list as well ? 
I think working with a session file is simpler, but perhaps sometimes there is no session file and you just want to run a list of tests ?

**Comment by ussfletcher** [comment]
This feature would be greatly appreciated.

**Comment by BinyaminSharet** [comment]
@0xd3d0  @ussfletcher I added the first (and hardest) part of it - which is support for non-sequential test lists (in the "next" branch) and even tested it a little. you can now use the
new fuzzer API: `set_test_list` or the command line argument '-t
--test-list' to run a specific list of tests.

**Comment by BinyaminSharet** [comment]
This is now implemented in the next branch, so I'm closing the issue.
