### ISSUE TITLE
web interface didn't display line break 

### ISSUE THREAD

**Issue by dark-lbp** [cisco-sas/kitty#52]
After i update to v6.0.7 the web interface didn't display line break any more. it's work in the old version.
![pic1](https://cloud.githubusercontent.com/assets/3477662/14626509/ace67090-061e-11e6-8e90-49e1d0cba87c.png)

**Comment by BinyaminSharet** [comment]
Yup. Will take care at that soon. 

However, I would suggest putting a shorter, one line reason, something like "A crush occurred at address XXXXXXXX", and set the entire crush report in a separate field ("crush report" maybe), sine the reason field is also used in the main page as some kind of summary. Still a bug though.

**Comment by dark-lbp** [comment]
OK,i will set the full crash report to other field.Thanks

**Comment by BinyaminSharet** [comment]
This issue is fixed in commit f718be61a3ecc832328b99a0b594178e084228c7 which is in the "next" branch. This branch will be merged with the master branch in the next release (in about 2 or 3 weeks, I guess).
