### ISSUE TITLE
Will Kitty compatible with python-scapy field?

### ISSUE THREAD

**Issue by dark-lbp** [cisco-sas/kitty#53]
In some case, i actually written some protocols using scapy. I like to use scapy to communication with target, but i prefer using Kitty to fuzz my target. 
Is there any better way to make kitty compatible with python-scapy field?

**Comment by dark-lbp** [comment]
By now, i just modify the "kitty/model/low_level/field.py" and add this code to the end.

```
# Scapy_Field
class Scapy_Field(BaseField):
    '''
    Represent a scapy_class
    '''

    _encoder_type_ = ScapyEncoder

    def __init__(self, value, encoder=ENC_SCAPY, fuzzable=True, name=None, fuzz_count=1000):
        '''
        :param value: scapy_packet_class
        :type encoder: :class:`~kitty.model.low_levele.encoder.ENC_SCAPYr`
        :param encoder: encoder for the field
        :param fuzzable: is field fuzzable (default: True)
        :param name: name of the object (default: None)
        :param fuzz_count: fuzz count (default: 1000)
        '''
        self.name = name
        self.fuzz_count = fuzz_count
        super(Scapy_Field, self).__init__(value=value, encoder=encoder, fuzzable=fuzzable, name=name)

    def hash(self):
        hashed = khash(self.name, type(self).__name__, self._fuzzable)
        return hashed

    def num_mutations(self):
        return self.fuzz_count
```
And "/kitty/model/low_level/encoder.py" 

```
# ScapyEncoder
class ScapyEncoder(object):
    '''
    Base encoder class for Scapy values
    The Scapy encoders *encode* function receives a *Scapy packet class* object as an argument and returns an encoded *Bits* object.
    '''

    def encode(self, value):
        '''
        :type value: ``str``
        :param value: value to encode
        '''
        # kassert.is_of_types(value, class)
        return Bits(bytes=str(value))
ENC_SCAPY = ScapyEncoder()
```
But By doing this i can only use scapy's random fuction. i think this may not a good way by compatible kitty and scapy.

**Comment by BinyaminSharet** [comment]
@dark-lbp I like the idea. importing formats of other fuzzers/libraries into kitty is something that we've been thinking about for a while. However, I don't think that it should be part of kitty. Maybe it can be part of Katnip, and maybe we need a separate package to handle data-model format conversion.

At this time, I don't think I will get to do that, as it requires dealing with scapy in a rather low level, and I don't have the experience to do it quick enough, nor the time to delve into that at this point. If you come  up with such a converting tool, please let me know, it can be the basis for a more generic tool to perform such conversions in the future.

**Comment by BinyaminSharet** [comment]
@dark-lbp I really liked your approach with the ScapyField and ScapyEncoder. I think it can be added to Katnip, which is a better place for it than Kitty (we try to avoid dependencies that aren't essential in Kitty).
Please consider contributing it to the Katnip repository.

Also, I have 3 notes/questions:

1. You might consider putting this field/encoder in a separate file, not inside of kitty. It should not be a problem, and will ease the development if you use Kitty from the Github repo and not pypi.
2. You don't need to assign ``self.name`` yourself in the ``__init__`` method, as this is already done by the super ``__init__`` call.
3. Out of curiosity - I didn't see where you actually mutate the scapy payload. When does scapy perform the mutation?

**Comment by dark-lbp** [comment]
@BinyaminSharet Thanks for your advice,I will try to putting this field/encoder in a separate file.

This is an example of using scapy field in kitty.
```
#!/usr/bin/python2
# -*- coding: utf-8 -*-
# import scapy
from scapy.all import *
from katnip.targets.tcp import *
from tcp_controller import *

from kitty.model import String, Scapy_Field
from kitty.model import Template
from kitty.interfaces import WebInterface
from kitty.fuzzers import ServerFuzzer
from kitty.model import GraphModel


packet = NTP()
t1 = Template(name='T1', fields=[
    Scapy_Field(fuzz(packet), name='S1_1', fuzzable=True),
])


# define target
target = TcpTarget(
    name='NTP target', host='172.16.229.191', port=102, timeout=2)

# define Controller
controller = Tcp_Port_Controller(
    name='TCP controller', logger=None, host='172.16.229.191', port=102)
target.set_controller(controller)

# define model
model = GraphModel()
model.connect(t1)

# define fuzzer
fuzzer = ServerFuzzer()
fuzzer.set_interface(WebInterface(port=26001))
fuzzer.set_model(model)
fuzzer.set_target(target)
# No need for delay, we only create files
# fuzzer.set_delay_between_tests(0.02)
# No need for range, generate all
# fuzzer.set_range(50)
fuzzer.start()

```
with scapy you can use fuzz() function to make payload mutate.
```
>>> packet=NTP()
>>> fuzz(packet).show2()
###[ NTP ]###
  leap= notsync
  version= 1L
  mode= broadcast
  stratum= 40L
  poll= 174L
  precision= 193L
  delay= 61881.2728424
  dispersion= 45866.6639099
  id= 26.48.25.37
  ref= Thu, 03 Mar 2005 09:04:25 +0000
  orig= Wed, 20 Apr 2016 06:21:42 +0000
  recv= 1616523190.59
  sent= Wed, 20 Apr 2016 06:21:42 +0000
>>> fuzz(packet).show2()
###[ NTP ]###
  leap= notsync
  version= 0L
  mode= server
  stratum= 136L
  poll= 120L
  precision= 209L
  delay= 64187.0598297
  dispersion= 17070.4582214
  id= 180.214.36.29
  ref= 915742346.605
  orig= Wed, 20 Apr 2016 06:21:43 +0000
  recv= 974024680.531
  sent= Wed, 20 Apr 2016 06:21:43 +0000
```

In ScapyEncoder i return str(value) which is same as str(fuzz(packet)). by doing that scapy will mutate the payload.
```
>>> str(fuzz(packet))
'Z\xd1\x08\x8b\xa3^\xdb0\xb1\x95n\xd0\xc5\x01V\x98\x01:\xe0\\\xd6:\xe6b\xda\xc1\x9f\x03\x1e\x9f\xb0\x00\x8e\x04\xd9\xb2\xe9?\x08\x11\xda\xc1\x9f\x03\x1e\xa2`\x00'
>>> str(fuzz(packet))
'{\x1c\xc4\x12\xb9\xc2^\xc9\xc9\x16B\xf5;r\xef^\x90\x13r_\x9fT4A\xda\xc1\x9f\x04\x1c\xb2\x10\x00\xc9\xd4\x15p\x8a\xc0\xb8\xb6\xda\xc1\x9f\x04\x1c\xb4\xa0\x00'
```

**Comment by BinyaminSharet** [comment]
@dark-lbp - That's cool. I have some more Qs. do you mind keep chatting in gitter? https://gitter.im/cisco-sas/kitty
