### ISSUE TITLE
StagedSequenceModel bug

### ISSUE THREAD

**Issue by ljcusack** [cisco-sas/kitty#62]
Example code and error produced:
http://pastebin.com/5crHecLn

mutate() and _mutate() both need to be called on Stage object and StagedSequenceModel objects respectively, this needs to be documented

After calling those, get_stages() can retrieve _sequence, but then tries to access it as a dictionary. Unfortunately I'm short on time and can't investigate this further for the current moment

Kind regards

**Comment by BinyaminSharet** [comment]
This issue happens because the environment test does not perform any mutation, and so mutate() is not called and there is no template sequence available. Until fixed, you can pass "-n" to the fuzzer via command line arguments or call "fuzzer.set_skip_env_test(True)" to skip the environment test.

**Comment by BinyaminSharet** [comment]
Fixed in the 'next' branch with commit 02f5bf297aebf27b9985965e7d7ec40cc518fca5 and will be part of release 0.7.0
