### ISSUE TITLE
how to mutate

### ISSUE THREAD

**Issue by whitepoet** [cisco-sas/kitty#83]
When I use Kitty, I use Kitty to conduct fuzzy testing of the protocol. One problem is how to call the mutation strategy to carry out data mutation after the data template is defined. I read the source code and did not solve this problem.I would appreciate an answer.

**Comment by BinyaminSharet** [comment]
If you use the entire fuzzing framework, the fuzzer will mutate the template before sending each message. If you are only using the data model (i.e. the template) and want to mutate it, you can call mutate and render in a loop:
```
t = Template(...)
while t.mutate():  # returns True when mutated, False when mutations exhausted.
    payload = t.render().tobytes()
    # do something with the payload
```

**Comment by GH0st3rs** [comment]
I use the next code:
```python
skip_count = 200
model = Template(...)
for _ in range(skip_count):
    model.mutate()
# start fuzzing from selected mutation
fuzzing(host, port, model)
```

**Comment by BinyaminSharet** [comment]
@whitepoet - I'm closing the issue, if you still have problems with it, please reply :)
