### ISSUE TITLE
Serverfuzzer - callback function is called before response is received

### ISSUE THREAD

**Issue by northoperator** [cisco-sas/kitty#84]
Hi, I am using kitty to create a REST API fuzzer.
I am sending a lot of HTTPS requests and need to check each response.
Thus I use a callback function for the purpose of checking the response on each request:

    def callbacker(fuzzer, edge, resp):
         print("RESPONSE:", resp)
    model = GraphModel()
    model.connect(http_template, None, callbacker)

In the current kitty version from pip, version 0.7.4, this functionality seems to be broken.
The problem is that the `resp` parameter for the callback function is always `None`.

Inside the `_run_sequence` method in `kitty/fuzzers/server.py`, I think I found the issue:

`edge.callback(self, edge, resp)` is called *before* `resp = self._transmit(node)`. Therefore, the callback is always called with `resp=None`.
(link to this line in the code: https://github.com/cisco-sas/kitty/blob/master/kitty/fuzzers/server.py#L69)

By moving these lines

    if edge.callback:
        edge.callback(self, edge, resp)

to right after the `resp = self._transmit(node)` line, the issue is now resolved and I can see the response in the callback function.

So: Is this a bug in the framework or am I using it incorrectly?

Thanks

**Comment by BinyaminSharet** [comment]
This is a bug. Callback is not well defined, and I will change that soon, after checking that it doesn't break some fuzzers that I know about.

Note, however:

1. Callback is called with `None` response only for the first request in a sequence, as it is called before the transmission. The next request in the sequence will be called with the latest response.

2. Sequence is not a session, but a sequence of payloads in which the last payload is mutated. So if you only have a single template in the sequence (as is in your case), the response will always be None.

**Comment by GH0st3rs** [comment]
Temporary, you can use next solution:
```python
def callbacker(fuzzer, edge, response):
    resp = fuzzer._transmit(edge.dst)
    if resp is not None:
        # do something

...
model = GraphModel()
model.connect(template, callback=callbacker)
```

Unfortunately, this leads to re-sending each request.

> [INFO    ][base._test_info] Current test: 1034
[INFO    ][server.transmit] request(3858): 474554202f6367692d62696e2 ...
[INFO    ][server.transmit] response(115): 485454502f312e3020323030204f4b0d0a ...
[INFO    ][server.transmit] request(3858): 474554202f6367692d62696e2 ...
[INFO    ][server.transmit] response(277): 485454502f312e3020323030204f4b0d0a ...
[INFO    ][base._test_info] Current test: 1035

**Comment by northoperator** [comment]
Any news @BinyaminSharet ? We are still using our patch to make our fuzzer work. Should we submit a pull request to fix this?

**Comment by BinyaminSharet** [comment]
@satvug Sorry for the delay. Yes - please submit a PR.
